export const productsVertical = [
  {
    category: "Smart tv",
    image: "/images/products/product1.png",
    name: "Sanung 85Q70A 85 Inch QLED 4K UHD Smart LED Television",
    type: "sale",
    price: "2036.00",
    oldPrice: "3000.00",
  },
  {
    category: "Cosmetics",
    image: "/images/products/product2.png",
    name: "Lomitech F310 - Wifi & USB RGB Dual Gamepad - for smooth experience",
    type: "new",
    price: "36.00",
    oldPrice: "40.00",
  },
  {
    category: "Headphone",
    image: "/images/products/product3.png",
    name: "Fabitech Sonata MH90 Multi-Platform RGB Gaming Headset",
    type: "sale",
    price: "124.00",
    oldPrice: "160.00",
  },
  {
    category: "Furniture",
    image: "/images/products/product4.png",
    name: "Sanung 85Q70A 85 Inch QLED 4K UHD Smart LED Television",
    type: "new",
    price: "124.00",
    oldPrice: "160.00",
  },
  {
    category: "Gaming",
    image: "/images/products/product5.png",
    name: "Sanung 85Q70A 85 Inch QLED 4K UHD Smart LED Television",
    type: "sale",
    price: "124.00",
    oldPrice: "160.00",
  },
  {
    category: "Headphone",
    image: "/images/products/product3.png",
    name: "Fabitech Sonata MH90 Multi-Platform RGB Gaming Headset",
    type: "sale",
    price: "124.00",
    oldPrice: "160.00",
  },
  {
    category: "Furniture",

    image: "/images/products/product4.png",
    name: "Sanung 85Q70A 85 Inch QLED 4K UHD Smart LED Television",
    type: "new",
    price: "124.00",
    oldPrice: "160.00",
  },
  {
    category: "Gaming",

    image: "/images/products/product5.png",
    name: "Sanung 85Q70A 85 Inch QLED 4K UHD Smart LED Television",
    type: "sale",
    price: "124.00",
    oldPrice: "160.00",
  },
];
export const productsFashion = [
  {
    category: "Smart tv",
    image: "/images/products/product-sm1.png",
    name: "Sanung 85Q70A 85 Inch QLED 4K UHD Smart LED Television",
    type: "sale",
    price: "2036.00",
    oldPrice: "3000.00",
  },
  {
    category: "Cosmetics",
    image: "/images/products/product-sm2.png",
    name: "Lomitech F310 - Wifi & USB RGB Dual Gamepad - for smooth experience",
    type: "new",
    price: "36.00",
    oldPrice: "40.00",
  },
  {
    category: "Headphone",
    image: "/images/products/product-sm3.png",
    name: "Fabitech Sonata MH90 Multi-Platform RGB Gaming Headset",
    type: "sale",
    price: "124.00",
    oldPrice: "160.00",
  },
  {
    category: "Furniture",
    image: "/images/products/product-sm4.png",
    name: "Sanung 85Q70A 85 Inch QLED 4K UHD Smart LED Television",
    type: "new",
    price: "124.00",
    oldPrice: "160.00",
  },
  {
    category: "Gaming",
    image: "/images/products/product-sm5.png",
    name: "Sanung 85Q70A 85 Inch QLED 4K UHD Smart LED Television",
    type: "sale",
    price: "124.00",
    oldPrice: "160.00",
  },
  {
    category: "Headphone",
    image: "/images/products/product-sm6.png",
    name: "Fabitech Sonata MH90 Multi-Platform RGB Gaming Headset",
    type: "sale",
    price: "124.00",
    oldPrice: "160.00",
  },
  {
    category: "Furniture",

    image: "/images/products/product-sm7.png",
    name: "Sanung 85Q70A 85 Inch QLED 4K UHD Smart LED Television",
    type: "new",
    price: "124.00",
    oldPrice: "160.00",
  },
  {
    category: "Furniture",

    image: "/images/products/product-sm7.png",
    name: "Sanung 85Q70A 85 Inch QLED 4K UHD Smart LED Television",
    type: "new",
    price: "124.00",
    oldPrice: "160.00",
  },
  {
    category: "Gaming",

    image: "/images/products/product-sm8.png",
    name: "Sanung 85Q70A 85 Inch QLED 4K UHD Smart LED Television",
    type: "sale",
    price: "124.00",
    oldPrice: "160.00",
  },
];
