export const portfolios = [
  {
    id: "1",
    title: "Headless CMS Blog",
    about: "Blog Site for Enterprise",
    tech: ["Next JS", "Typescript", "contentfull CMS", "Tailwind CSS"],
    images: ["/images/project1/1.png", "/images/project1/2.png"],
    role: "Frontend Developer",
    github: "https://github.com/Shahriar-Shakil/haque-timbers-saw-mill",
    live: "https://haquetimbersbd.netlify.app/",
    description:
      "<p>Headless CMS Blog is a modern and responsive blog site built with <strong>Next JS</strong> and <strong>Typescript</strong>, featuring <strong>Contentful CMS</strong> integration and a beautiful user interface powered by <strong>Tailwind CSS</strong>. The site is designed to cater to enterprise-level requirements and can be easily customized to fit any organization's branding and content needs.</p><p>As a <strong>Frontend Developer</strong> on this project, I worked on designing and developing the user interface with a focus on user experience and ease of navigation. I also integrated the site with Contentful CMS, providing the client with a flexible and scalable way to manage their blog content.</p>",
  },
  {
    id: "2",
    title: "E-commerce",
    about: "Next JS e-commerce",
    tech: ["Next JS", "Recoil", "Tailwind CSS"],
    images: [
      "/images/project2/1.png",
      "/images/project2/2.png",
      "/images/project2/3.png",
      "/images/project2/4.png",
    ],
    role: "Frontend Developer",
    github: "https://github.com/Shahriar-Shakil/e-commerce-next-app",
    live: "https://mart-next.netlify.app/",
    description:
      "<p>E-commerce is a stunning and responsive Next JS application designed and developed as a code assessment project in 2021. The project utilizes <strong>Recoil</strong> and <strong>Tailwind CSS</strong> to provide a smooth and responsive user interface, showcasing a beautiful e-commerce platform inspired by the popular <em>MartFury</em> theme on ThemeForest.</p><p>As a <strong>Frontend Developer</strong>, my role in this project was to design and develop the user interface and implement the e-commerce functionality",
  },
  {
    id: "3",
    title: "React SaaS applications",
    about: "",
    tech: ["Next JS", "Recoil", "Tailwind CSS", "SWR"],
    images: [
      "/images/project3/1.png",
      "/images/project3/2.png",
      "/images/project3/3.png",
      "/images/project3/4.png",
    ],
    role: "Frontend Developer",
    github: "",
    live: "https://originfe.vercel.app/",
    description:
      "<p>My React SaaS applications project is a modern and responsive web application built using Next JS, Recoil, Tailwind CSS, and SWR. The project showcases my expertise in building scalable and reliable web applications with an emphasis on user experience and performance.</p><p>As a Frontend Developer, my role in this project was to design and develop the user interface and implement the necessary functionality for a SaaS application. The project features a modern and responsive user interface with seamless navigation, intuitive user flows, and fast loading times.</p><p>The React SaaS applications project is a great example of my proficiency in modern web development technologies and my ability to deliver high-quality work in a timely and efficient manner. ",
  },
  {
    id: "3",
    title: "MyFarmBD - Empowering Finance and Food Security in Bangladesh",
    about: "",
    tech: ["Next JS", "Redux", "Scss", "SWR"],
    images: [
      "/images/project4/1.png",
      "/images/project4/2.png",
      "/images/project4/3.png",
      "/images/project4/4.png",
      "/images/project4/5.png",
      "/images/project4/6.png",
      "/images/project4/7.png",
      "/images/project4/8.png",
      "/images/project4/9.png",
    ],
    role: "Frontend Developer",
    github: "",
    live: "https://www.myfarmbd.com/",
    description:
      "<p>MyFarmBD is a platform that enables people to contribute to achieving food security for Bangladesh while also growing their funds. With a simple, safe, and sustainable investment platform, investors can support real farmers in growing food for the Bangladeshi population. The platform offers a spectrum of investable farms, allowing micro-investors and high network individuals alike to invest in the cause of food security for Bangladesh and achieve financial freedom. </p><p>As a Frontend Developer on this project, I used Next.js and SWR for API calling, Redux for state management, and integrated with the Laravel backend. MyFarmBD's user interface is designed to be user-friendly, engaging, and responsive, with a focus on delivering an intuitive and streamlined user experience. </p>",
  },
];
